HashMap
mycelium/hsai-java-2023 pull request #158
Opened 2022-10-18 13:15 UTC by coockie273

Прикрепляю вторую работу. У меня так и не получилось придумать, как реализовать метод setStep() и получить ошибку компиляции, если задание step бессмысленно. Думал над вариантом с интерфейсами, т.е. для каждой стратегии поиска создавать новый объект интерфейса (а не объект самого класса HashMap), основанный на определенной стратегии поиска, и для него выделять ссылку на класс HashMap, но такая идея мне совершенно не понравилась , поэтому прошу какого-то намёка на другую реализацию этого приёма. В Main.java попробовал написать какие-то тесты.

2022-10-18 16:44 UTC, dmirosh commented
@coockie273 идея с общим интерфейсом, но отдельными классами, со своим API для каждой стратегии вполне рабочая и часто используемая. Почему она вам не нравится?
Еще есть вариант с хитрым билдером, я его на лекции покажу

2022-10-25 18:35 UTC, coockie273 commented
Попробовал реализовать изменение step через создание разных билдеров, получилось, возникает ошибка во время компиляции, но выглядит это кривовато, так как не удалось избежать копипаста в билдерах.

2022-10-25 20:13 UTC, dmirosh requested changes

2022-10-25 20:13 UTC, dmirosh commented on lesson6/homework/src/HashMap/HashMap.java
> +    HashMapElement[] table;
Модификаторы доступа принято делать максимально строгими. Иными словами, если можно делать что-то private, значит надо делать private

2022-10-25 20:13 UTC, dmirosh commented on lesson6/homework/src/HashMap/HashMap.java
> +    public static QuadraticBuilder quadraticBuilder() {
Да, именно об этом подходе к билдерам я говорил, но можно сделать еще чуть более аккуратно  - всегда создавать билдер через один метод `builder()` а потом менять на нужные через вызов типа `setLinearStrategy()`

2022-10-25 20:13 UTC, dmirosh commented on lesson6/homework/src/HashMap/HashMap.java
> +            HashMap.this.capacity = capacity;
Тут не критично, но вцелом любую повторяющуюся логику лучше выносить в базовый клас (я понимаю, что переопределить метод все равно прийдется)

2022-10-25 20:13 UTC, dmirosh commented on lesson6/homework/src/Helpers/HashMapElement.java
> +    public void setHashCode(int hashCode) {
Какой-то сложный алгоритм работы с этим классом получается - вначале создаем с дефолтным хешкодом, потом надо не забыть поменять. Попробуйте сделать класс рекордом с неизменяемыми полями, будет надежнее

2022-10-25 20:13 UTC, dmirosh commented on lesson6/homework/src/Search/LinearSearch.java
> +public class LinearSearch extends AbstractSearch {
Что на счет почти копи-паста тут и в классе ConsistentSearch?

2022-10-26 16:57 UTC, coockie273 commented
Попытался исправить всё, о чём вы написали, но возникли некоторые трудности:
1) Я попробовал создавать билдер через единый метод, а потом уже менять его на конкретный билдер. У меня не получилось, так как при возвращении нового билдера в методах set...Strategy все изменения, внесенные в поля HashMap не сохраняются ( из-за создания нового билдера). Выхода из этой ситуации я не нашёл, поэтому, пока что, оставил так.
2) По поводу зацикливания в linear стратегии - я думал об этом, но потом, на лекции вы сказали, что этот случай можно не обрабатывать, поэтому я решил сильно в это не вдумываться (Если необходимо я попытаюсь решить эту проблему).

2022-10-26 19:58 UTC, dmirosh commented
1.Билдер покажу на лекции.
2. Все правильно, это не главное

2022-10-26 20:00 UTC, merged