Homework 5
mycelium/hsai-java-2023 pull request #160
Opened 2022-10-19 20:53 UTC by bumashka

Практически всё переделала, добавила всё в новую папку lesson5. Со степом так и не разобралась, падает только в рантайме из-за каста.

2022-10-20 13:29 UTC, bumashka commented
Сделала из HashElement рекорд, добавила общее поле отвечающее за tombStone

2022-10-25 19:54 UTC, dmirosh requested changes

2022-10-25 19:54 UTC, dmirosh commented on lesson5/homework/src/HashTable/HashTable.java
> +    OrdinaryInterface table;
Принято модификаторы доступа делать наиболее строгими. Если можно сделать поле приватным, значит надо его делать

2022-10-25 19:54 UTC, dmirosh commented on lesson5/homework/src/HashTable/HashTable.java
> +    public void setStep(int s) {
Мне казалось после лекции должно стать понятно как избежать этого приведения типов. Паттерн "Стратегия" тут все еще хорошо смотрится

2022-10-25 19:54 UTC, dmirosh commented on lesson5/homework/src/HashTable/LinearHashMap.java
> +                if (Objects.nonNull(hashTable[hashValue]) && hashTable[hashValue]!=tombStone && hashTable[hashValue].key().equals(k)) {
Не забывайте про форматирование. Не хотите руками каждый раз применять - настройте автоматическое применнеие в ide

2022-10-25 19:54 UTC, dmirosh commented on lesson5/homework/src/HashTable/OrdinaryHashMap.java
> +    int step;
модификаторы доступа

2022-10-30 08:27 UTC, merged