Homework5 belyaev
mycelium/hsai-java-2023 pull request #188
Opened 2022-10-28 21:40 UTC by fug0

2022-10-28 21:43 UTC, fug0 commented
Отправил уже немного после дедлайна, конечно, но как получилось...

2022-10-30 09:53 UTC, dmirosh requested changes

2022-10-30 09:53 UTC, dmirosh commented on lesson5/homework/src/HashMap/HashMap.java
> +public class HashMap implements HashMap_Interface {
В java не принято использовать snake case для именования классов и переменных

2022-10-30 09:53 UTC, dmirosh commented on lesson5/homework/src/Main.java
> +            System.out.println("GETORELSE method are correct.");
Более-менее похоже на тесты, но они требуют ручного просмотра, хотелось бы от этого избавиться

2022-10-30 09:53 UTC, dmirosh commented on lesson5/homework/src/SearchStrategy/QuadraticSearch.java
> +        hash += q * q;
Не нашел обработки переполнения массива

2022-10-30 09:53 UTC, dmirosh commented on lesson5/homework/src/SearchStrategy/SearchStrategy_Abstract.java
> +        if (this instanceof QuadraticSearch) {
Обычно когда нужно делать instanceof не где-то в одном специально выделенно месте, а посредине "рабочего" кода, это признак плохого дизайна

2022-10-30 09:53 UTC, dmirosh commented on lesson5/homework/src/HashMap/HashMap_Element.java
> +    public static HashMap_Element tombStone = new HashMap_Element("", null);
Такие объекты принято делать константами

2022-10-30 10:23 UTC, closed without merging