lab3
mycelium/hsai-java-2023 pull request #189
Opened 2022-10-31 17:57 UTC by coockie273

Работа выполнена не до конца, возникла пара проблем, которые я не смог решить:
1) При парсинге бита, равного более 127, число превосходит положительную часть числа типа byte, поэтому оно становится отрицательным. Из-за этого символы закодированные такими битами выводятся некорректно, казалось бы, можно проигнорировать числа типа byte и просто конвертировать интовские числа, но я не смог найти способа конвертировать int в символ в НУЖНОЙ кодировке.
2) Кодировка UTF-16 отказывается работать, как бы я ни старался, в консоль выводятся вопросики(??), как с ней бороться я не знаю.....
Это 2 случая некорректной работы алгоритма, остальное должно работать хорошо.

2022-11-07 19:45 UTC, dmirosh commented
По поводу вопросов:
1. Не понял проблемы, в джаве байты со знаком, т.е. от -128 до 127. В задании на вход подаются беззнаковые, действительно нужно конвертнуть. Как это сделать легко гуглится
2. Если это винда, то лечится в настройках консоли. Там нужно поменять кодировку на Utf16. Но можете вместо этого тоже в какой-то файл записать

2022-11-07 22:48 UTC, coockie273 commented
Дело не в том, чтобы перевести число из незнакового в знаковое, при переводе числа в знаковое, оно становится отрицательным и конструктор String, преобразующий байты в строку, не может понять, что за символ кроется за числом-127 и т.д., хотя число 128 распознаётся отлично, в этом и заключается трудность.

2022-11-08 09:03 UTC, coockie273 commented
Также, вы не оставили комментариев по поводу работоспособности моего текущего алгоритма...

2022-11-08 15:39 UTC, coockie273 commented
Немного покопался в своей работе, нашёл небольшой баг, теперь коды >127 корректно воспринимаются в UTF-8 кодировке, но они также не хотят восприниматься в ASCII, UTF-16 также не работает, смена кодировки не помогает в обоих случаях.

2022-11-10 06:16 UTC, dmirosh commented
Теперь работает, но мои замечания касательно кода не поправлены.
Принято, но с оговорками

2022-11-10 10:47 UTC, dmirosh requested changes

2022-11-10 12:42 UTC, coockie273 commented
Постарался исправить все замечания

2022-11-29 18:20 UTC, dmirosh commented on lesson5/homework/src/BytesReader.java
> +            throw new NoSuchFileException(fileName);
Обман! Ведь файл может существовать, а проблема совсем в другом.
Кроме того почти никогда не стоит игнорировать исходное исключение

2022-11-29 18:21 UTC, merged