Первая домашняя работа по массиву
mycelium/hsai-java-2023 pull request #33
Opened 2022-09-12 04:03 UTC by Benhooky

Боюсь сильно накосячил с ветками и, скорее всего, тут явно что-то не так, надеюсь на пояснения по поводу своих ошибок )

2022-09-12 19:40 UTC, dmirosh requested changes

2022-09-12 19:40 UTC, dmirosh commented on lesson1/homework/src/com/hsai/home1/README.md
> +## Getting Started
Дефолтное ридми обычно никакой пользы не несет. Не стоит его коммитить.

2022-09-12 19:40 UTC, dmirosh commented on lesson1/homework/src/com/hsai/home1/Script.txt
> +#!binsh
У шел скриптов обычно другое расширение.
и shebang чуть-чуть не так пишется.
В канал скинул небольшой гайд по башу

2022-09-12 19:40 UTC, dmirosh commented on lesson1/homework/src/com/hsai/home1/Script.txt
> +java -jar home1.jar
В задании написано, что скрипт должен собирать, а не запускать приложение. Смотрите пример
Ну и по названию скрипта всегда должно быть хоть немного понятно, что он делает. По названию`Script` ничего не понятно.

2022-09-12 19:40 UTC, dmirosh commented on lesson1/homework/src/com/hsai/home1/src/App.java
> +        System.out.println("Hello, World!");
Это можно писать для тестов, в реальной программе (а у нас реальная) такому не место

2022-09-12 19:40 UTC, dmirosh commented on lesson1/homework/src/com/hsai/home1/src/App.java
> +        int[] ArrForSort=Arrays.copyOfRange(BaseArray,1,BaseArray.length);
Отформатируйте код (согласно общепринятому стайлгайду операторы отделяются одним пробелом)
Во всех IDE для форматирования есть горячие клавиши, постарайтесь использовать их

Также с большой буквы пишутся только классы, переменные указываются с маленькой. Просмотрите гайд - https://google.github.io/styleguide/javaguide.html

2022-09-12 19:40 UTC, dmirosh commented on lesson1/homework/src/com/hsai/home1/src/App.java
> +        String EasyMenu[] = {"Insert Sort","Selecrion Sort","Merge Sort","Quick Sort",};
Опечатка

2022-09-12 19:40 UTC, dmirosh commented on lesson1/homework/src/com/hsai/home1/src/App.java
> +        Scanner in = new Scanner(System.in);
Массив передается в программу как аргументы командной строки (смотрите пример вызова в тикете), т.е. в параметре `args` функуции `main`
C stdin чуть позже будем работать

2022-09-12 19:40 UTC, dmirosh commented on lesson1/homework/src/com/hsai/home1/src/App.java
> +        switch (SortNumber){
В задаче отдельно обращено внимание, что номер может быть как отрицательным, так и больше (по-модулю), чем количество элементов в массиве.

2022-09-12 19:40 UTC, dmirosh commented on lesson1/homework/src/com/hsai/home1/src/App.java
> +                MergeSort.MergeSort(ArrForSort,ArrForSort.length);
Алгоритмы делают одно и то же - сортируют массив, неудобно когда у них разные интерфейсы - в какие-то передаем массив, в другие массив с длиной

2022-09-12 19:40 UTC, dmirosh commented on lesson1/homework/src/com/hsai/home1/src/App.java
> +        System.out.println("Время выполнения сортировки, мс: " + elapsed);
Оценка времени выполнения это хорошо, но функциональными требованиям не стоит пренебрегать. В задаче указан точный формат вывода. Обычно это делается для того, чтобы можно было запустить автоматический чекер, если вы будете использовать произвольный, то он ответ не засчитает

2022-09-12 19:40 UTC, dmirosh commented on lesson1/homework/src/com/hsai/home1/src/MergeSort/MergeSort.java
> +package MergeSort;
Разбиение по пакетам очень важно. Когда все классы лежат в одном это неудобно. Но также неудобно, когда на один класс один пакет, нужно искать золотую середину. Тут, я думаю, можно завести один пакет `algorihm` или что-то такое, куда положить все алгоритмы

2022-09-12 19:40 UTC, dmirosh commented on lesson1/homework/src/com/hsai/home1/src/SelecrionSort/SelecrionSort.java
> +        arr[i] = (arr[i] + arr[j]) - (arr[j] = arr[i]);
Красивый трюк, но нечитаемо. Таких коллег не любят

2022-09-12 20:46 UTC, Benhooky commented on lesson1/homework/src/com/hsai/home1/README.md
> +## Getting Started
Убрал его.

2022-09-12 20:48 UTC, Benhooky commented on lesson1/homework/src/com/hsai/home1/Script.txt
> +#!binsh
Да, спасибо, этот удалил и новый потом добавлю

2022-09-12 20:48 UTC, Benhooky commented on lesson1/homework/src/com/hsai/home1/src/App.java
> +        System.out.println("Hello, World!");
Случайно не убрал, всё почистил.

2022-09-13 18:44 UTC, dmirosh requested changes

2022-09-13 18:44 UTC, dmirosh commented on .vscode/launch.json
> +{
Настройки IDE обычно не коммитятся. Все-таки у каждого может быть свой редактор

2022-09-13 18:44 UTC, dmirosh commented on lesson1/homework/src/com/hsai/home1/src/App.java
> +        while (sort_number<0){
Все еще форматирование страдает

2022-09-13 18:44 UTC, dmirosh commented on lesson1/homework/src/com/hsai/home1/src/alghorithm/insert_Sort.java
> +public class insert_Sort{
Имя класса не соответствует общепринятым правилам. Смотрите стайлгайд

2022-09-23 16:32 UTC, merged