Task1wip
mycelium/hsai-java-2023 pull request #49
Opened 2022-09-18 20:54 UTC by Sakralen

2022-09-19 18:55 UTC, dmirosh requested changes

2022-09-19 18:55 UTC, dmirosh commented on lesson1/homework/src/com/hsai/SortApp.java
> +            default:
Пустой дефолт не лучше, чем его отсутствие. Хотя бы заллогируйте неожиданный аргумент, а лучше еще и работу закончите

2022-09-19 18:55 UTC, dmirosh commented on lesson1/homework/src/com/hsai/auxclasses/AlgDeterm.java
> +    public static int Determine(int inp) {
Название метода не соответствует стайлгайду.
В некоторых других местах тоже  есть неверное форматтирование. Поправьте, пожалуйста. Для этого необязательно везде руками искать, можно воспользоваться соответствующей функцией IDE
Ну и над названием параметра явно долго не думали

2022-09-19 18:55 UTC, dmirosh commented on lesson1/homework/src/com/hsai/sortalgs/MergeSort.java
> +//https://www.geeksforgeeks.org/merge-sort/
"+" за то, что подумали про читателей

2022-09-20 12:16 UTC, Sakralen reviewed
Всё поправлено

2022-09-21 18:09 UTC, dmirosh approved these changes

2022-09-21 18:09 UTC, merged